<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_INR()_icon-close</name>
   <tag></tag>
   <elementGuidId>ccd0940f-b791-4a60-a816-82104a59dc41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginModal']/div/div/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0e6e16ca-b2dc-4789-8c66-5cf92a6a2f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-close</value>
      <webElementGuid>5240b3cc-69ad-4072-9472-d9b7f92f7c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginModal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered login-modal&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;auth-box&quot;]/button[@class=&quot;close&quot;]/i[@class=&quot;icon-close&quot;]</value>
      <webElementGuid>3b8328c7-4036-47d5-adea-de8bde708117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginModal']/div/div/div/button/i</value>
      <webElementGuid>6aa4b319-ef1c-4d0c-8152-5ac98ea8ec89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button/i</value>
      <webElementGuid>c2f35200-d817-4a43-909e-fb1f6dd88e3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
