<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NumberCVC</name>
   <tag></tag>
   <elementGuidId>490a8be1-7320-4efe-9d36-85e54c55891a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/form/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.CardField-input-wrapper.is-ready-to-slide</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5417a7d8-474c-48df-81a2-de6c388842fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CardField-input-wrapper is-ready-to-slide</value>
      <webElementGuid>e56dea2b-e54f-42e8-9348-b9dd70d5529f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>a50fea91-c04f-4e9e-b8cb-2b557499e02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NumberCVC</value>
      <webElementGuid>1091807d-4fc0-479b-b3b6-7027289a9b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/form[@class=&quot;ElementsApp is-empty is-focused&quot;]/div[@class=&quot;CardField CardField--ltr&quot;]/div[@class=&quot;CardField-input-wrapper is-ready-to-slide&quot;]</value>
      <webElementGuid>51828bf0-ed6c-4215-8e6d-4598857aed1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Shopping Cart - Yaathi- Marketplace/iframe_Edit___privateStripeFrame9876</value>
      <webElementGuid>5d16a41f-4ee6-457b-883a-1d1bbec7adb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/form/div/div[2]</value>
      <webElementGuid>0c73ec89-4706-408f-9b39-3849f1709d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>b2dbf05c-b556-46cd-a31c-ae6dc76ebf2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NumberCVC' or . = 'NumberCVC')]</value>
      <webElementGuid>1c1eefe3-0d08-4fbc-882d-f051dc301a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
