<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Edit___privateStripeFrame9876</name>
   <tag></tag>
   <elementGuidId>2c6f4a0d-94e5-46e3-a6bd-20db10daf8c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='__privateStripeFrame9876']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;__privateStripeFrame9876&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6d32f1de-4f7f-477f-946f-a7ce817fc35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame9876</value>
      <webElementGuid>4a929188-29b3-4a84-b66d-61ac4423e239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d4e45c64-767a-4291-a0db-514155fa3d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74150827-731c-46e8-9cc9-3711fbea3b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>db99cf09-3822-4b10-b99c-330ccbdbfd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>67a013ed-39b5-4f36-a12a-fa43ff8516a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>payment *</value>
      <webElementGuid>ea792105-63c5-42db-9d6e-3fdb87eaedf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-aa2aefc13fdbeeb3f598209e8fdc612e.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=%2332325d&amp;style[base][lineHeight]=38px&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;rtl=false&amp;componentName=card&amp;keyMode=test&amp;apiKey=pk_test_51LcimSSBPyNx0mD9FqYCbMbD4RVRScbjDCY8tASYL88ZnXYDSojTAZ7j38XSQEAtYKIA7jpoqIywUnCJB7m4ppGQ007hjIZyyk&amp;referrer=https%3A%2F%2Fmarketplace.iihtsrt.com%2Fcart%2Fpayment&amp;controllerId=__privateStripeController9871</value>
      <webElementGuid>ed81d679-fa00-44c9-948b-92e6b71560c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure card payment input frame</value>
      <webElementGuid>343cfddf-e363-44d0-87cd-e93d5a841a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card-element&quot;)/div[@class=&quot;__PrivateStripeElement&quot;]/iframe[1]</value>
      <webElementGuid>e0452459-0666-4c25-8ac8-3b4766da5abb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='__privateStripeFrame9876']</value>
      <webElementGuid>a8e23151-d338-4410-a21f-4f5c13e0059c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card-element']/div/iframe</value>
      <webElementGuid>09008367-9be8-40d4-9ba4-1eda67893f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6caf912d-48c8-4260-bb62-c7f45f283d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = '__privateStripeFrame9876' and @src = 'https://js.stripe.com/v3/elements-inner-card-aa2aefc13fdbeeb3f598209e8fdc612e.html#wait=false&amp;mids[guid]=NA&amp;mids[muid]=NA&amp;mids[sid]=NA&amp;style[base][color]=%2332325d&amp;style[base][lineHeight]=38px&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;rtl=false&amp;componentName=card&amp;keyMode=test&amp;apiKey=pk_test_51LcimSSBPyNx0mD9FqYCbMbD4RVRScbjDCY8tASYL88ZnXYDSojTAZ7j38XSQEAtYKIA7jpoqIywUnCJB7m4ppGQ007hjIZyyk&amp;referrer=https%3A%2F%2Fmarketplace.iihtsrt.com%2Fcart%2Fpayment&amp;controllerId=__privateStripeController9871' and @title = 'Secure card payment input frame']</value>
      <webElementGuid>8f2546bf-b9ec-4a44-97fd-7f4c1bf573f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
