<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sarees</name>
   <tag></tag>
   <elementGuidId>9ffe65ec-d1b5-4e75-b26f-038e65c2dbfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav_main_category_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav_main_category_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e91683c-5d15-4af9-b6bf-95a6495ac85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav_main_category_1</value>
      <webElementGuid>19959f93-0ac7-4b85-9d41-1a80f11a687b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://marketplace.iihtsrt.com/indian-wear/sarees</value>
      <webElementGuid>713a7de5-e23b-4b3e-9b6c-f05961b699b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>second-category nav-main-category</value>
      <webElementGuid>81d3597c-0111-4edd-8eec-14a5fbe4b8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e3111dd8-9375-44d8-830d-b9a1d337ce7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent-id</name>
      <type>Main</type>
      <value>77</value>
      <webElementGuid>0a68d15b-c39a-43b5-ad67-5e6b286df786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-has-sb</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a3e7415-884c-4817-9779-35b1440da4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sarees</value>
      <webElementGuid>8e7bd635-7f24-4216-b08c-d6ad88c1f4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_main_category_1&quot;)</value>
      <webElementGuid>8d2c379a-654b-4fa8-840e-e39d31585f2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav_main_category_1']</value>
      <webElementGuid>3144374a-dee5-416f-aa9a-8b04b69454cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='large_menu_content_77']/div/div/div/a</value>
      <webElementGuid>8c2956df-57b0-44c9-95de-0d005f08603e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sarees')]</value>
      <webElementGuid>968302b8-9af8-48a9-a351-c8216dc36b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STYLE'])[1]/preceding::a[1]</value>
      <webElementGuid>94ee6427-fd72-47f0-a3b4-6608f3c34eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OCCASION'])[1]/preceding::a[2]</value>
      <webElementGuid>f769e35d-1b9c-4295-9336-ad7ae1732507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sarees']/parent::*</value>
      <webElementGuid>528ed199-f28d-4d0b-8b05-4c99bed11b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://marketplace.iihtsrt.com/indian-wear/sarees')]</value>
      <webElementGuid>cd092104-e4ec-4304-ab9f-6c130274d9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/a</value>
      <webElementGuid>51a055a9-797f-4d89-8cc6-1e7a85190153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav_main_category_1' and @href = 'https://marketplace.iihtsrt.com/indian-wear/sarees' and (text() = 'Sarees' or . = 'Sarees')]</value>
      <webElementGuid>b6500cf3-f624-48ea-8f70-24ac542b3a48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
