<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_STYLE</name>
   <tag></tag>
   <elementGuidId>beda2f10-e6a4-49cb-acd8-6dacace4b725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav_main_category_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav_main_category_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>440eded4-33ac-4a9d-8ff0-6aa5838d9f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav_main_category_3</value>
      <webElementGuid>f7ed7652-f557-480f-bc93-86988c5c3b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://marketplace.iihtsrt.com/sarees/style</value>
      <webElementGuid>e60ecfc3-d87c-4892-bf60-f7b2f8d04888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-main-category </value>
      <webElementGuid>44627154-b95f-4118-b3ce-523ac30fb4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c9a60759-12b6-4fbe-8077-2906db5bc0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>78e3c7e3-7b5a-4351-825d-3f29a5ac6294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-has-sb</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c0c5e42d-df8d-486a-b0bc-7d9a4303a39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>STYLE</value>
      <webElementGuid>b2f81e0f-9e7c-4435-b074-6f5ae14b2961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_main_category_3&quot;)</value>
      <webElementGuid>0de97d9f-8c85-4ca3-844c-d246ba2f505b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav_main_category_3']</value>
      <webElementGuid>32b58108-349d-4d5d-8744-c63a472b06da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='large_menu_content_77']/div/div/div/ul/li/a</value>
      <webElementGuid>0928eff3-4e75-4d36-9791-1eab285f662a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'STYLE')]</value>
      <webElementGuid>ccfc08d0-763b-42b8-8e64-92cf8349e9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sarees'])[1]/following::a[1]</value>
      <webElementGuid>7bbea304-bbe3-4341-9fad-f19383314b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OCCASION'])[1]/preceding::a[1]</value>
      <webElementGuid>64bcddf4-2887-4310-a224-df0b965cb8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FABRIC'])[1]/preceding::a[2]</value>
      <webElementGuid>f8fa643d-699e-44ff-8e18-97f1e19769a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='STYLE']/parent::*</value>
      <webElementGuid>16051aed-9a69-4ebe-8d8d-c7713ce87b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://marketplace.iihtsrt.com/sarees/style')]</value>
      <webElementGuid>24065087-df1b-4057-82f0-5971175fba74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/ul/li/a</value>
      <webElementGuid>a035451b-37d5-43e8-9726-11e9d7d077f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav_main_category_3' and @href = 'https://marketplace.iihtsrt.com/sarees/style' and (text() = 'STYLE' or . = 'STYLE')]</value>
      <webElementGuid>a2ace4a0-270d-43e0-84a6-13970ea45d92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
