<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Length (cm)_field_1</name>
   <tag></tag>
   <elementGuidId>25d93cd7-4847-41d0-8c85-3ddce1bafd9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='field_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;field_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afd021e6-3b9f-4b41-bd58-b5a399672e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>15c2972d-10c3-40d6-ac40-78dcf0d07414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_1</value>
      <webElementGuid>ab09a5d9-024b-4982-b088-ffcb71960ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input</value>
      <webElementGuid>1edf999b-fc7f-4580-a90c-a66182f1d97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Length (cm)</value>
      <webElementGuid>7bd2c79e-de9b-40f3-939b-8e41fa85cbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d93e77c1-0617-4d7f-80cf-c4f7f15ca976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999999</value>
      <webElementGuid>f1f2fbcc-4cf4-4afc-a878-af3a9c7731ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_fields_container&quot;)/div[@class=&quot;col-sm-12 col-sm-6 col-custom-field&quot;]/input[@class=&quot;form-control form-input&quot;]</value>
      <webElementGuid>38714cc0-c174-4c35-a269-6caa9f987ac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='field_1']</value>
      <webElementGuid>1a3ac0a1-5147-4975-96ab-3a59562534c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom_fields_container']/div/input</value>
      <webElementGuid>4416521d-476b-4bf7-986f-d2c1945a8cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>5946c5f6-c51b-4d15-81a4-7b3d109dd76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'field_1' and @placeholder = 'Length (cm)']</value>
      <webElementGuid>8a0a3346-f560-46c3-81c0-23af65bca76b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
