<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SEO_seo_keywords_1</name>
   <tag></tag>
   <elementGuidId>f4b5cd82-71b2-4bcc-adb4-76414aa5bb65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='seo_keywords_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;seo_keywords_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46d276f3-33b3-4f09-9ce7-94750dbf3a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4606929a-7491-4418-849d-a7919ed535fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>seo_keywords_1</value>
      <webElementGuid>667f2e76-74f1-43f0-9e0d-68672ec2fd6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input m-b-5</value>
      <webElementGuid>a65ac577-d3b2-4a64-880c-a9ea6425c7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Keywords (E.g. book, new, pencil)</value>
      <webElementGuid>8efa5fe0-cc52-47ee-bef1-23e7254c55e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>490</value>
      <webElementGuid>b7d99aad-b753-4e36-a696-9cd05ca70024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse_1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-input m-b-5&quot;]</value>
      <webElementGuid>2678f986-e0c9-4cf8-aedb-64d5b2cb94d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='seo_keywords_1']</value>
      <webElementGuid>cd927ed2-56e8-42af-878a-143d0e4c8c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse_1']/div/div[3]/input[3]</value>
      <webElementGuid>18df4506-e7fd-4ccb-bf06-82584c1bbc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[3]</value>
      <webElementGuid>da78422d-8aaa-4d82-ad63-9ef22caa824f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'seo_keywords_1' and @placeholder = 'Keywords (E.g. book, new, pencil)']</value>
      <webElementGuid>c0e619c8-7c0f-4ebb-b02b-11d97f249487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
