<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Height (cm)_field_3</name>
   <tag></tag>
   <elementGuidId>20c3177a-1b93-44d3-af99-9e98022523c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='field_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;field_3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>503d28dc-6096-4464-851b-801393f412f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>dd6f1c21-7794-4b7d-b709-118a3d04b81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_3</value>
      <webElementGuid>deb5ade1-fb54-4512-8693-89872115797e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input</value>
      <webElementGuid>f4e787e1-28c8-4796-9743-5240a73a99c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Height (cm)</value>
      <webElementGuid>51926e69-5cbb-4a95-ba4f-dc166da4bd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fd3d58a9-db1b-4220-b49b-b5d68f169398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999999</value>
      <webElementGuid>51ba17c1-a944-4fc2-b1f7-7b8e2bbacb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_fields_container&quot;)/div[@class=&quot;col-sm-12 col-sm-6 col-custom-field&quot;]/input[@class=&quot;form-control form-input&quot;]</value>
      <webElementGuid>72a524bb-ddc5-4b53-9503-463117c3a96c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='field_3']</value>
      <webElementGuid>5ab9db8b-2ba6-4c5a-a384-e62f010fe5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom_fields_container']/div[3]/input</value>
      <webElementGuid>0f3cf817-8bf7-4fc9-b37a-8c00d785ca46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>4c743b00-b598-4039-9eec-f9072d46447b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'field_3' and @placeholder = 'Height (cm)']</value>
      <webElementGuid>55bfab38-4d6d-4043-adc6-dccdf7b6e323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
