<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Product Code)_sku</name>
   <tag></tag>
   <elementGuidId>b8d91b0c-959b-40fc-99e7-eb8ccee1ca3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_sku']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_sku</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27b9b8e2-c33f-42fc-af93-fd272523c151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5063bc0-0681-4a03-afc9-be9a26458d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sku</value>
      <webElementGuid>6f321cf4-9c2c-418f-a71d-6204f4a272b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_sku</value>
      <webElementGuid>e8a97b00-d8ac-4006-907e-8ff1c88244a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input</value>
      <webElementGuid>919b8ad5-a9f5-44a0-a616-464485056cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SKU (Optional)</value>
      <webElementGuid>de077074-23e0-46fc-8790-cfbd429cf665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>29823b34-fef2-4ff6-be5f-d256aeb7ffa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_sku&quot;)</value>
      <webElementGuid>8388cd7d-733a-47bf-af78-ee1750c8a98c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_sku']</value>
      <webElementGuid>b9520ce2-0e2e-46f9-9c41-974c546b0d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_product_details']/div[2]/div/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>dfb5baa9-8c79-4abc-9d34-278f1ad0d0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>40528301-efeb-4f31-b67e-1852e9af1eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'sku' and @id = 'input_sku' and @placeholder = 'SKU (Optional)']</value>
      <webElementGuid>1b8d6d14-bdb0-4168-80f4-a5319f311a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
