<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3d5a963d-96a8-455f-a838-f8874475f2df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div/div[2]/ul/li/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;storeadmin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>efe2c69a-2bbe-4fc3-b79e-9f7e0a7de709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://marketplace.iihtsrt.com/uploads/profile/avatar_62d935830a3035-85770603-19851657.jpg</value>
      <webElementGuid>f5183741-d91f-4f01-ad50-1dc842a70698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>storeadmin</value>
      <webElementGuid>393bb475-1f40-41b1-9e08-7dd1d2d918f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;top-bar&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 col-right&quot;]/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item dropdown profile-dropdown p-r-0&quot;]/a[@class=&quot;nav-link dropdown-toggle a-profile&quot;]/img[1]</value>
      <webElementGuid>408d4008-2649-4ed7-aa52-8a2fc9fbbcde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div/div[2]/ul/li/a/img</value>
      <webElementGuid>ce0c3626-bb10-4089-8c02-182afaca44ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='storeadmin']</value>
      <webElementGuid>de46738b-f1c6-4d51-b2eb-21be0dde8279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>05ff0c25-c347-47e2-b8ef-14c2f041c9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://marketplace.iihtsrt.com/uploads/profile/avatar_62d935830a3035-85770603-19851657.jpg' and @alt = 'storeadmin']</value>
      <webElementGuid>e42cdcdc-c41d-439b-b7d1-d0ff5880a618</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
