<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pay3,650</name>
   <tag></tag>
   <elementGuidId>44ef63b3-65a4-48a3-8d7a-092f2a49ba9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rzp-button1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='rzp-button1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7a451d1-783c-4dda-84a1-3986dda82f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a594ead-d6bc-46ea-b78e-ce7b1f3e6a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rzp-button1</value>
      <webElementGuid>4f77c1e1-4243-4761-83dd-d53f066b5df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-payment btn-razorpay</value>
      <webElementGuid>542d8eb3-d9fe-4734-a0c4-3957a533bae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay ₹3,650</value>
      <webElementGuid>fdd17036-44c2-4a90-8e82-e693a63c4720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rzp-button1&quot;)</value>
      <webElementGuid>f154259b-6965-431d-82a7-792a74a2c737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='rzp-button1']</value>
      <webElementGuid>6f5c018d-1e34-4d11-829b-f664537cfa3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-button-container']/button</value>
      <webElementGuid>d9035cbe-9512-41a5-8da6-d82c194292e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/following::button[1]</value>
      <webElementGuid>b09a83d5-c8e8-4c84-8447-6f0773143b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::button[1]</value>
      <webElementGuid>7fa2ec0b-ed23-4839-b0fa-adce93f5f10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary (1)'])[1]/preceding::button[1]</value>
      <webElementGuid>56b06c47-c302-4ce0-8504-4c109638146a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>33bf86d7-7f10-4a35-a163-03f6eb92d8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'rzp-button1' and (text() = 'Pay ₹3,650' or . = 'Pay ₹3,650')]</value>
      <webElementGuid>ce5d7975-37a7-4b40-b89c-53ad1ee5fd2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
