<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proceed</name>
   <tag></tag>
   <elementGuidId>8355499a-07d2-4e06-ad4d-a4afe312cef7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#redesign-v15-cta</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='redesign-v15-cta']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e5ea492-23fb-4e8e-bf83-a11432d3f01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>redesign-v15-cta</value>
      <webElementGuid>713a4b7f-497a-438f-b200-8e2ee26d23a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svelte-1qxsru6</value>
      <webElementGuid>2d8e77c2-27eb-4985-a3b9-1e63232a9b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed</value>
      <webElementGuid>5ad75f32-b5b8-4260-931e-4b20ef06c7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;redesign-v15-cta&quot;)</value>
      <webElementGuid>68e20406-7988-4929-92ef-75d2a51ef759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/marketplace04/Page_Shopping Cart - Yaathi- Marketplace/iframe_Test Mode_razorpay-checkout-frame</value>
      <webElementGuid>2cf1789e-fead-41d0-8d9b-8a5f7a7b796e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='redesign-v15-cta']</value>
      <webElementGuid>9baf23e6-08fc-4ddd-a671-f7dcf76da53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[3]/div/button</value>
      <webElementGuid>0faa2128-8539-412c-9575-2e599d222310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secured by'])[4]/following::button[1]</value>
      <webElementGuid>7c2a89d5-c210-45dd-b795-0bdf1bc832e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[4]/following::button[1]</value>
      <webElementGuid>7f5ff482-1883-4f85-a3c5-07db6d6dab52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::button[2]</value>
      <webElementGuid>8410957d-7cde-4373-8908-e267d210fbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed']/parent::*</value>
      <webElementGuid>ccb475e8-7cd1-4f5f-be64-21eb59513067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>2a9f3572-f917-4377-8e5d-27012cf4b4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'redesign-v15-cta' and (text() = 'Proceed' or . = 'Proceed')]</value>
      <webElementGuid>614f9665-4694-4caf-8783-7b978856ed38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
