<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Test Mode_razorpay-checkout-frame</name>
   <tag></tag>
   <elementGuidId>e6aee60e-f9b3-4b71-a163-f9469979507b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.razorpay-checkout-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>80f82078-b241-4279-8fd4-9f049ec1c5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c60c506-fb40-4dd1-8adf-cc8aa60af81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c00e9fa-48d1-45d7-a72b-8ac5edaa7b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>550d8ff8-00e6-4456-84ea-17910ab189a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>435a294f-1225-4dab-87e4-ca9a8c457366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowpaymentrequest</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f5b534b1-8a40-49a6-ae97-83af9ad9a63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.razorpay.com/v1/checkout/public?traffic_env=production&amp;build=126f9f21929289bb8280117be30e4c11856e05d4</value>
      <webElementGuid>f72d3423-c72e-4303-93b1-ec37d1be16f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>razorpay-checkout-frame</value>
      <webElementGuid>be42b68a-3234-443a-96ef-461ee3dacddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;razorpay-container&quot;]/iframe[@class=&quot;razorpay-checkout-frame&quot;]</value>
      <webElementGuid>0f176dc5-e796-47e6-b525-d0f23afc83c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>03407394-9dea-4056-8291-2ec280ad09d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://api.razorpay.com/v1/checkout/public?traffic_env=production&amp;build=126f9f21929289bb8280117be30e4c11856e05d4']</value>
      <webElementGuid>ca0b0c85-8e9a-4b02-9891-bb081bd8fa30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
