<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Razorpay</name>
   <tag></tag>
   <elementGuidId>86e08624-5468-49a9-b0d3-a0103de331a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_validate']/div/div/div/ul/li[3]/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f606a72a-db68-400d-90c5-fdf9cacab92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label label-payment-option</value>
      <webElementGuid>a17c5367-f8ab-47d2-828e-06ab5435247d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>option_4</value>
      <webElementGuid>be455406-c1b3-4361-981b-3ed4e3da7c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Razorpay</value>
      <webElementGuid>1388e212-afbf-45d4-9a0d-71a49eda523c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_validate&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;form-group&quot;]/ul[@class=&quot;payment-options-list&quot;]/li[3]/div[@class=&quot;option-payment&quot;]/div[@class=&quot;list-left&quot;]/div[@class=&quot;custom-control custom-radio&quot;]/label[@class=&quot;custom-control-label label-payment-option&quot;]</value>
      <webElementGuid>2797c95b-551c-49e7-b966-6fe8c434dec7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_validate']/div/div/div/ul/li[3]/div/div/div/label</value>
      <webElementGuid>aafdb978-c310-4d77-97d2-a3c4e1fe02ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stripe'])[1]/following::label[2]</value>
      <webElementGuid>d4235e0b-21eb-4525-9d60-efaca33a5e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayPal'])[1]/following::label[4]</value>
      <webElementGuid>5d9a93df-1443-4691-94a5-1f1c8af7e2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay with cash upon delivery.'])[1]/preceding::label[2]</value>
      <webElementGuid>cfd511e4-de94-454a-9c85-73396d97c77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Razorpay']/parent::*</value>
      <webElementGuid>9a8d0140-f6ba-4591-910d-5213d626e03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/label</value>
      <webElementGuid>d31b286e-96a9-4052-9133-91bd97c07dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Razorpay' or . = 'Razorpay')]</value>
      <webElementGuid>2971f7ab-1c3b-4ac2-a792-115a9791e621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
