<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Paragraph_editor_1_ifr</name>
   <tag></tag>
   <elementGuidId>fab873f6-03c5-4443-960d-c1b09522a94e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editor_1_ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='editor_1_ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>53b88a5e-14b2-40ab-b215-dc218dffe2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editor_1_ifr</value>
      <webElementGuid>2799e239-756a-4569-943e-fcf478e8d514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e977de94-e778-471f-85fb-49e7eb598425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dce80e14-5eb8-4067-afda-ee4453ebee69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area. Press ALT-0 for help.</value>
      <webElementGuid>a57ce88e-cd2c-4c26-858e-a4aba5dc15b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>4af674ac-5d1a-44c5-b807-794498d71a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editor_1_ifr&quot;)</value>
      <webElementGuid>d6aaf5b7-6004-4fd4-a757-3a3a0c44a46a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='editor_1_ifr']</value>
      <webElementGuid>8b38ec0e-572e-40b6-8c21-bd3964fa4833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse_1']/div/div[2]/div[2]/div/div[2]/div/iframe</value>
      <webElementGuid>167091a2-f276-48d1-9a15-08fbecf4d209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e3e84b58-b4de-40c5-aa47-9166ad52698c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'editor_1_ifr' and @title = 'Rich Text Area. Press ALT-0 for help.']</value>
      <webElementGuid>d69d1288-16bf-47a2-be7c-4215f6289656</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
