<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_password</name>
   <tag></tag>
   <elementGuidId>489f62e4-1d26-4563-8956-f8c50e32e61d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d02a252e-c689-4936-8007-5bb1bfdbe80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>13e1cb17-e28f-4b0a-ac50-3064fd7cae6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>33f32501-9349-4431-95f5-09bf2cf3b048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control auth-form-input</value>
      <webElementGuid>eb51ca27-81a7-4a9a-a630-7b06ce11a53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>28e9d715-9d2d-4431-9db5-f61aa8708127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ee4718ef-4ef0-49a1-a8c7-97df60a996de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>7e0ed935-7a07-4556-8429-97adaead8d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_login&quot;)/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control auth-form-input&quot;]</value>
      <webElementGuid>4b5749f4-2d36-456c-96eb-ddece8b592ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>c255417c-a921-43e3-84d3-6dbcddac3588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_login']/div[4]/input</value>
      <webElementGuid>314c0101-7f5f-482c-af88-f52c4baa0742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>c64f37a1-03ad-4d8d-9131-ae04b815265f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>d0c02c94-ace6-44cf-bf19-b77e410c7815</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
