<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sell Now</name>
   <tag></tag>
   <elementGuidId>09ff38db-4f06-4784-b255-0a63ee89a2ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[2]/div/div/div/div/div/div[2]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-md.btn-custom.btn-sell-now.m-r-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c7c6a8a5-37de-47e7-9b3f-959b0731abc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://marketplace.iihtsrt.com/dashboard/add-product</value>
      <webElementGuid>8c055b96-a42e-4b04-943a-45fbb438f861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-md btn-custom btn-sell-now m-r-0</value>
      <webElementGuid>76425182-0870-4673-885e-026009d5209a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sell Now</value>
      <webElementGuid>c49365fa-3c49-4d59-8f18-4bea607e887a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;main-menu&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;nav-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-md-4 nav-top-right&quot;]/ul[@class=&quot;nav align-items-center&quot;]/li[@class=&quot;nav-item m-r-0&quot;]/a[@class=&quot;btn btn-md btn-custom btn-sell-now m-r-0&quot;]</value>
      <webElementGuid>6fc61e9b-2ce8-40bf-8f1e-f68e7117e101</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div/div/div/div/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>edf9725c-519f-4454-b700-2b6380c0b68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sell Now')]</value>
      <webElementGuid>5e7da988-206e-411e-97a0-1e77f4e776a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::a[2]</value>
      <webElementGuid>46bddd70-a874-4146-86df-6a123c1243f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Women'])[1]/preceding::a[1]</value>
      <webElementGuid>6f6bb1a4-9720-44c8-8cba-43fd282bd4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sell Now']/parent::*</value>
      <webElementGuid>43e54c25-7998-4d90-b6dd-c85d7838ef01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://marketplace.iihtsrt.com/dashboard/add-product')]</value>
      <webElementGuid>c6e78af2-ee1f-43b3-a034-867b8b28ae55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>64e1254a-ba9b-4a5a-a4e2-612cf569bd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://marketplace.iihtsrt.com/dashboard/add-product' and (text() = 'Sell Now' or . = 'Sell Now')]</value>
      <webElementGuid>35f25ded-d4de-47f9-9041-2c31fe72a136</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
