<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sell Now</name>
   <tag></tag>
   <elementGuidId>4972bea1-328e-45b7-a790-ff1290f2e33b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[2]/div/div/div/div/div/div[2]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-md.btn-custom.btn-sell-now.m-r-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7f95c1f-7b8a-4fa1-8217-4286369ff820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://marketplace.iihtsrt.com/dashboard/add-product</value>
      <webElementGuid>627657d2-5eaf-4883-9c88-0e044b248ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-md btn-custom btn-sell-now m-r-0</value>
      <webElementGuid>074dd627-6914-4965-ba36-eb87ebf051d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sell Now</value>
      <webElementGuid>bc28d4d6-da86-4698-b20a-4a887d11a522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;main-menu&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;nav-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-md-4 nav-top-right&quot;]/ul[@class=&quot;nav align-items-center&quot;]/li[@class=&quot;nav-item m-r-0&quot;]/a[@class=&quot;btn btn-md btn-custom btn-sell-now m-r-0&quot;]</value>
      <webElementGuid>aa05ad4f-a120-4e6e-b75d-f686058c4623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[2]/div/div/div/div/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>372efe05-9383-4dd4-9a21-3ae4273a1993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sell Now')]</value>
      <webElementGuid>7ad9f2d1-5170-40ec-a747-46fa28795d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::a[2]</value>
      <webElementGuid>f23b7952-b76f-4c8e-a701-2d8633984ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Women'])[1]/preceding::a[1]</value>
      <webElementGuid>0b9364c1-204d-409c-a2ba-0bbcf7e51b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sell Now']/parent::*</value>
      <webElementGuid>9618d089-c0ec-4211-83dd-d8166f68fa61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://marketplace.iihtsrt.com/dashboard/add-product')]</value>
      <webElementGuid>fda2dcb7-1555-476f-bd90-f53f2e4f496f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]/a</value>
      <webElementGuid>aebdaad3-be0a-4ebe-b0b1-caa1e507a710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://marketplace.iihtsrt.com/dashboard/add-product' and (text() = 'Sell Now' or . = 'Sell Now')]</value>
      <webElementGuid>b9e19df2-7fdd-4255-8d59-7c8f70216802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
