<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Reset_img-responsive</name>
   <tag></tag>
   <elementGuidId>10d01f79-63a4-41f2-a8a9-4a0a6a4e4714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ckimg_col_id_8']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ckimg_col_id_8 > div.file-box > div.image-container > img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>daa17808-50de-473b-b967-3f735f0e9c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://marketplace.iihtsrt.com/uploads/images-file-manager/202207/img_62de31bbd20da6-68832512-54727746.jpg</value>
      <webElementGuid>775d3a2a-184a-47c7-986a-c869356b915d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>32e63bb9-4cc7-4f5f-af10-179f3c796b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ckimg_col_id_8&quot;)/div[@class=&quot;file-box&quot;]/div[@class=&quot;image-container&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>eae16d83-515a-4ce6-b83f-18c99ac4ad99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ckimg_col_id_8']/div/div/img</value>
      <webElementGuid>43cd76ec-dfbe-492a-8314-6d2a040b7670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://marketplace.iihtsrt.com/uploads/images-file-manager/202207/img_62de31bbd20da6-68832512-54727746.jpg')]</value>
      <webElementGuid>ae90c0d1-e229-4480-8118-1c09867f3023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img</value>
      <webElementGuid>b51ae288-cfbc-4c7d-b288-5d9a324b0bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://marketplace.iihtsrt.com/uploads/images-file-manager/202207/img_62de31bbd20da6-68832512-54727746.jpg']</value>
      <webElementGuid>032b9b4b-cf4c-4a60-abaf-d95e03c1f958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
