<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SEO_seo_keywords_1</name>
   <tag></tag>
   <elementGuidId>cac1a1eb-1dc7-470a-8633-26c0a206bfac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='seo_keywords_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;seo_keywords_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc6cb5a5-54da-43c8-bdfb-cb54e469d0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de7a3a4d-b55b-4527-b43e-8a12b4f76b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>seo_keywords_1</value>
      <webElementGuid>c196d10a-0152-4423-9b55-55c96a790842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input m-b-5</value>
      <webElementGuid>82a4e8fb-3150-4f1f-a494-c5be5cfc83ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Keywords (E.g. book, new, pencil)</value>
      <webElementGuid>d3774c86-b27f-49c7-be92-396812ee5d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>490</value>
      <webElementGuid>62f8088d-5cd6-43be-a91d-e0e50e37f09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse_1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-input m-b-5&quot;]</value>
      <webElementGuid>37adb885-7210-4f30-8725-137384d6ba69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='seo_keywords_1']</value>
      <webElementGuid>a10b27ff-6012-45e3-a3fd-cccf8891ef10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse_1']/div/div[3]/input[3]</value>
      <webElementGuid>fde154ae-b5d2-40b3-9efc-364f1de57830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[3]</value>
      <webElementGuid>1fc0adf5-67e9-4a2c-b7f9-2d9427ee473e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'seo_keywords_1' and @placeholder = 'Keywords (E.g. book, new, pencil)']</value>
      <webElementGuid>8b3c18a0-7e63-4b0b-907f-9d1ae3df20e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
