<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select CategoryBeltsEyewear  Sunglas_36c07c</name>
   <tag></tag>
   <elementGuidId>842a9701-58fd-4bac-872a-782768d23b28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@name='category_id[]'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7d1a6260-4867-4bda-befa-81c7c7cb40eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-select</value>
      <webElementGuid>5ae56581-73ba-4e7d-8fff-ece2e9a4f809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_id[]</value>
      <webElementGuid>752f1fd4-7ce1-4140-8f99-8c6339b86691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select-id</name>
      <type>Main</type>
      <value>1665557150117</value>
      <webElementGuid>9dc24903-dedc-42e7-b5de-bd28700991e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>get_subcategories(this.value,1665557150117);</value>
      <webElementGuid>c2bd19fa-2c0f-40aa-8c83-b7414640a181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CategoryBeltsEyewear &amp; SunglassesGlovesHair AccessoriesHats &amp; CapsHeadphonesHealth EssentialsScarves &amp; MufflersShawlsSmart WatchesSocksSpeakersStolesWatches</value>
      <webElementGuid>69adaf2b-9be2-494e-ae3e-ee23c2004c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_select_container&quot;)/select[@class=&quot;form-control custom-select&quot;]</value>
      <webElementGuid>aefbc2f9-796e-4eee-95e0-75e26dc0fa50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@name='category_id[]'])[3]</value>
      <webElementGuid>80a4830a-2204-43e9-b2ba-3f103c40729b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_select_container']/select[2]</value>
      <webElementGuid>18275b1a-a7a3-47ba-bbb2-05760a61caec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::select[3]</value>
      <webElementGuid>48cf49d9-a3a2-4210-b5f4-3087387a588f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse Files'])[1]/following::select[3]</value>
      <webElementGuid>ead715d7-18e3-46ab-bca7-4c944ba11885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/preceding::select[1]</value>
      <webElementGuid>3e8abfa9-ddc3-40f3-9ddb-1e84e320c282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>59f5a9ae-254a-4602-8c2c-1c7655b14902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'category_id[]' and (text() = 'Select CategoryBeltsEyewear &amp; SunglassesGlovesHair AccessoriesHats &amp; CapsHeadphonesHealth EssentialsScarves &amp; MufflersShawlsSmart WatchesSocksSpeakersStolesWatches' or . = 'Select CategoryBeltsEyewear &amp; SunglassesGlovesHair AccessoriesHats &amp; CapsHeadphonesHealth EssentialsScarves &amp; MufflersShawlsSmart WatchesSocksSpeakersStolesWatches')]</value>
      <webElementGuid>8fce1878-7d12-453b-bbf9-5a011c271c40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
