<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Reset_img-responsive</name>
   <tag></tag>
   <elementGuidId>6c4817f6-1db2-4a47-b682-48c2b9d3ca80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ckimg_col_id_9']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ckimg_col_id_9 > div.file-box > div.image-container > img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5827e787-305d-4475-b631-3fbdfd4b42e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://marketplace.iihtsrt.com/uploads/images-file-manager/202207/img_62e6a97eeff3b2-79377895-15707913.jpg</value>
      <webElementGuid>55ca773f-e963-4747-a27a-2fb0abd9107a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>f9998976-5a11-4305-8413-cd3d114cb222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ckimg_col_id_9&quot;)/div[@class=&quot;file-box&quot;]/div[@class=&quot;image-container&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>991544c0-cdc2-4566-80e5-07f8a3d72f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ckimg_col_id_9']/div/div/img</value>
      <webElementGuid>32c0fd19-53e3-49da-bf01-b4f90ef85827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://marketplace.iihtsrt.com/uploads/images-file-manager/202207/img_62e6a97eeff3b2-79377895-15707913.jpg')]</value>
      <webElementGuid>e4378b84-d7cc-49f5-94b6-686684ad9cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>331cbec3-9dde-46eb-a26f-5bd825300cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://marketplace.iihtsrt.com/uploads/images-file-manager/202207/img_62e6a97eeff3b2-79377895-15707913.jpg']</value>
      <webElementGuid>4fde7786-5eb6-4a9a-bc59-f795d897c3a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
