<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Breadth (cm)_field_2</name>
   <tag></tag>
   <elementGuidId>1169299b-2a66-4a90-92ea-7962c79f4e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='field_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;field_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a97d0a9-3912-4ed7-8008-dd543ee4ff40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e039684d-d793-4d31-b018-18c25a4b15cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_2</value>
      <webElementGuid>cb23e118-8370-4103-9b77-64b11ebca281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input</value>
      <webElementGuid>cd74495f-7eed-4e9f-907f-0a05961711a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Breadth (cm)</value>
      <webElementGuid>164731f7-2825-421a-8924-6682f842448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>51c1d494-a173-48e6-bae6-ca42d8f5cdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999999</value>
      <webElementGuid>d3ff24b1-90fc-4870-9646-ecd33f8a8bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_fields_container&quot;)/div[@class=&quot;col-sm-12 col-sm-6 col-custom-field&quot;]/input[@class=&quot;form-control form-input&quot;]</value>
      <webElementGuid>87ef529e-fabc-4509-ba34-cfff857e30ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='field_2']</value>
      <webElementGuid>b57d627c-13f2-4923-b5a3-3f76c9a56e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom_fields_container']/div[2]/input</value>
      <webElementGuid>c8c8b7f9-b852-483f-b951-b41f35689132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>15652a7b-b151-4389-81ef-181372de7d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'field_2' and @placeholder = 'Breadth (cm)']</value>
      <webElementGuid>f85f3e30-e689-490a-9e52-541102920f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
