<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SEO_seo_title_1</name>
   <tag></tag>
   <elementGuidId>ad68420b-27d5-49e9-a7d3-b20642853f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='seo_title_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;seo_title_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fab9bdaf-3205-4d8a-92a7-e00d31c1b5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>615c2ac8-0dc1-4a65-af9a-63ae2d1e6b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>seo_title_1</value>
      <webElementGuid>f6230e48-ad38-4fb4-9eb0-4e9520a26a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input m-b-5</value>
      <webElementGuid>83b22b12-fd14-47a0-a25f-9b44f465ff4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>6afa8d8a-d3d9-496a-a5fe-abc67b06cf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>490</value>
      <webElementGuid>28667d53-b5c4-45c3-a319-ebfe3ddb66ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse_1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-input m-b-5&quot;]</value>
      <webElementGuid>8b92efa1-f86c-42d8-9818-d1b13215f1fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='seo_title_1']</value>
      <webElementGuid>1bf69fa3-1069-48b6-88c6-4a4e1ba644af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse_1']/div/div[3]/input</value>
      <webElementGuid>e0242dba-29d8-418a-bffc-f93275fb575b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>c5346aba-59ce-480f-81b1-68215b983bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'seo_title_1' and @placeholder = 'Title']</value>
      <webElementGuid>512f5882-0f95-425c-acb8-df527652388e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
