<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Weight(in kg)_field_4</name>
   <tag></tag>
   <elementGuidId>85d366ac-d103-4ba4-97c1-afe97579e6c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='field_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;field_4&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>624862ea-f37d-4130-8803-bad26b8535b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d8cb248-1ad4-41ea-a55d-fdca23102296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_4</value>
      <webElementGuid>033d20d0-d4d6-4f01-8164-78b1d6758109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input</value>
      <webElementGuid>6844b1bc-3dc6-45ab-87ca-90727d9cb2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Weight(in kg)</value>
      <webElementGuid>9b6f7acc-59c0-4c13-a0de-f8de1f466ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_fields_container&quot;)/div[@class=&quot;col-sm-12 col-sm-6 col-custom-field&quot;]/input[@class=&quot;form-control form-input&quot;]</value>
      <webElementGuid>83e4c53b-f451-4072-9b92-20f8d79f1572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='field_4']</value>
      <webElementGuid>6596a1c3-f842-480b-bb68-abc9d7ff2a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom_fields_container']/div[4]/input</value>
      <webElementGuid>14cef353-9f61-41b6-86a2-6eb96f1ee269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>ba5109ef-c0b0-4707-be51-01b633d09faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'field_4' and @placeholder = 'Weight(in kg)']</value>
      <webElementGuid>d15bc989-3125-44b9-a3de-796de4715c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
