<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SEO_seo_description_1</name>
   <tag></tag>
   <elementGuidId>af55862b-5108-4d5e-bc73-1a676843c013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='seo_description_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;seo_description_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29f0fa4a-00c4-4b22-9164-cd22b7a454b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90be94d4-fb42-430b-926f-1d9cfe1037d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>seo_description_1</value>
      <webElementGuid>c22af861-0385-4aac-9b9f-68cfcd4bac40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-input m-b-5</value>
      <webElementGuid>3d1fa5a9-33ca-4177-a697-64e93581b131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>23ab0b67-9ce4-4229-a862-4f0a01f72ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>490</value>
      <webElementGuid>0d81866b-48d1-47e5-bb5c-b6bcb2605b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse_1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-input m-b-5&quot;]</value>
      <webElementGuid>0e76e83b-3e68-4d08-acbf-3b2863d7561d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='seo_description_1']</value>
      <webElementGuid>0968426b-1e2c-41de-82bc-9bab3d90abc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse_1']/div/div[3]/input[2]</value>
      <webElementGuid>7295bbbb-30b7-4847-8374-0cf610cff6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>f254f4d5-61ed-49e9-8b74-5f2de2edcb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'seo_description_1' and @placeholder = 'Description']</value>
      <webElementGuid>66f7a076-6cb4-4545-8f34-0efa92769dff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
