<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Green</name>
   <tag></tag>
   <elementGuidId>a7af17bd-d5e6-4c6a-88b6-0134efd30833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkbox_options_container_5']/div/div[2]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>016da09c-b0fe-48b4-bbb2-38f80f7635ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>3ce7f053-58e6-4c7b-a136-4167999d7a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>form_checkbox_3</value>
      <webElementGuid>f675ff58-0c38-44af-a6cb-3b0406620573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Green</value>
      <webElementGuid>0d9dcfc6-4af7-4fd6-8936-4d693afb5b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox_options_container_5&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-sm-3 col-custom-option&quot;]/div[@class=&quot;custom-control custom-checkbox custom-control-validate-input label_validate_field_5&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
      <webElementGuid>80189f68-9871-494f-ac35-5db1c13c5e71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkbox_options_container_5']/div/div[2]/div/label</value>
      <webElementGuid>47712e67-af9d-4420-94da-f1e47133dbd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue'])[1]/following::label[1]</value>
      <webElementGuid>72e1a1b3-b885-4462-be5f-c0c54b87f14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Colors'])[1]/following::label[2]</value>
      <webElementGuid>0cecc9a4-f1f5-4e73-936a-25de97fe04f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Red'])[1]/preceding::label[1]</value>
      <webElementGuid>a6bd019d-5bce-42d3-ae9e-b64393b81194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/preceding::label[2]</value>
      <webElementGuid>69bdf162-e5f5-455e-b51e-7b8da2aa8fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Green']/parent::*</value>
      <webElementGuid>bd5c9ca9-c5f9-43a5-b817-bf2539a7bf84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>e814f396-a80b-4f51-aa9d-c17d4c27916f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Green' or . = 'Green')]</value>
      <webElementGuid>18ace622-9170-4790-9255-44c929b81eb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
