<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Casual</name>
   <tag></tag>
   <elementGuidId>c3f01807-a757-4912-be17-190c128ef0d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkbox_options_container_9']/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.custom-control.custom-checkbox.custom-control-validate-input.label_validate_field_9 > label.custom-control-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8b79e4ff-834e-4e05-8325-d9ac11f672da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>5229e161-171f-4197-8021-8178b69e0317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>form_checkbox_10</value>
      <webElementGuid>707d995f-70a3-44bd-82b7-f0a87af35316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Casual</value>
      <webElementGuid>6db32481-47f9-460d-9729-f4966df63f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox_options_container_9&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-sm-3 col-custom-option&quot;]/div[@class=&quot;custom-control custom-checkbox custom-control-validate-input label_validate_field_9&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
      <webElementGuid>cba2a2a6-9570-44d1-b85f-3f8cf33756c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkbox_options_container_9']/div/div/div/label</value>
      <webElementGuid>c31c083c-bdb1-4a4d-bc00-37a9dd18b06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occasion'])[1]/following::label[1]</value>
      <webElementGuid>d3af9b7d-e835-4b0b-b809-0a7999e724d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='xl'])[1]/following::label[2]</value>
      <webElementGuid>77468c29-8af3-4f76-8aa9-32ef060abd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock'])[1]/preceding::label[1]</value>
      <webElementGuid>de974172-9388-4f6a-829a-230e04267a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Casual']/parent::*</value>
      <webElementGuid>6836730a-09dd-4cb6-8101-14402c8289fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/label</value>
      <webElementGuid>17dcc912-7ccc-45b9-8cff-7a213444683d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Casual' or . = 'Casual')]</value>
      <webElementGuid>b90af6ab-f99f-43b6-a923-6b997c2a00c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
