<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Red</name>
   <tag></tag>
   <elementGuidId>7361739e-9a8b-4c25-9bb1-6136d2597bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkbox_options_container_5']/div/div[3]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>095f5ba8-7067-4d9c-933a-291510d12b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>1a5059f5-e1fc-4efe-8658-7b755eec3ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>form_checkbox_1</value>
      <webElementGuid>c55d1825-021a-461c-bd1f-6df4aebe7d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Red</value>
      <webElementGuid>d0b43d1f-2022-416c-aadb-a8a555b1932b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox_options_container_5&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-sm-3 col-custom-option&quot;]/div[@class=&quot;custom-control custom-checkbox custom-control-validate-input label_validate_field_5&quot;]/label[@class=&quot;custom-control-label&quot;]</value>
      <webElementGuid>12e3bffc-a3b1-46d0-ac15-8e10be6d81a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkbox_options_container_5']/div/div[3]/div/label</value>
      <webElementGuid>4d272f91-cd99-4e33-8651-e6cb4dc2da1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Green'])[1]/following::label[1]</value>
      <webElementGuid>cc3ff4da-0dd4-48fb-8608-8da8e407b1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue'])[1]/following::label[2]</value>
      <webElementGuid>2e5defb4-63d3-4e5a-b518-330055219485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/preceding::label[1]</value>
      <webElementGuid>3fe8d25c-f2c0-4b52-9a2e-ea01db638e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sarees'])[1]/preceding::label[2]</value>
      <webElementGuid>5e006df7-23e0-4057-ac86-867342f45e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Red']/parent::*</value>
      <webElementGuid>a4ca10de-93de-4321-ad33-09ce7c3c42da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label</value>
      <webElementGuid>081311d0-432b-4c56-86a0-efc6bcf8ac39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Red' or . = 'Red')]</value>
      <webElementGuid>c6521afe-3506-4fee-a8b3-95ea46d20476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
