<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select CategoryBottomsCardigansCo-or_584e4b</name>
   <tag></tag>
   <elementGuidId>cf1854f7-08e5-4751-a82a-43bd502654f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@name='category_id[]'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>11c951e9-f6ba-4939-86e3-73307b3d8a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-select</value>
      <webElementGuid>55d9e6e9-0c6b-4006-9885-de2466c863aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category_id[]</value>
      <webElementGuid>bc75a8fc-2342-44cc-b0f1-46cad8dadab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select-id</name>
      <type>Main</type>
      <value>1665724096155</value>
      <webElementGuid>73064cf1-a785-4cf3-be68-7ae16948d7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>get_subcategories(this.value,1665724096155);</value>
      <webElementGuid>c2c972d7-62cd-4dd3-a34e-c079377a782d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CategoryBottomsCardigansCo-ord SetsDressesGownsJacketsJeans &amp; JeggingsJumpsuitsShirtsSkirtsSweatshirtsT-shirtsTops</value>
      <webElementGuid>f08d2bcf-7a15-4f2d-949d-fc172037338a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_select_container&quot;)/select[@class=&quot;form-control custom-select&quot;]</value>
      <webElementGuid>51266cb8-4b9e-4816-9bdf-9bbc9c0c2510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@name='category_id[]'])[3]</value>
      <webElementGuid>22afd2b9-1ac3-4ffb-8a0c-9c5d0ed30ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='category_select_container']/select[2]</value>
      <webElementGuid>9b675714-67c4-4bc5-8f67-ceafc9a724f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::select[3]</value>
      <webElementGuid>2b071719-e114-4d59-8ceb-61c4a2105e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse Files'])[1]/following::select[3]</value>
      <webElementGuid>66afb6c3-eae6-43d3-a5a5-a4642146c1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/preceding::select[1]</value>
      <webElementGuid>476c58fb-483f-43a6-9862-1d42d89dc0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>5790800a-d0a0-4661-a41a-af2564991961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'category_id[]' and (text() = 'Select CategoryBottomsCardigansCo-ord SetsDressesGownsJacketsJeans &amp; JeggingsJumpsuitsShirtsSkirtsSweatshirtsT-shirtsTops' or . = 'Select CategoryBottomsCardigansCo-ord SetsDressesGownsJacketsJeans &amp; JeggingsJumpsuitsShirtsSkirtsSweatshirtsT-shirtsTops')]</value>
      <webElementGuid>4d620055-d411-4668-953a-48a06fb9a1fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
